---
version: "2"
services:
  config-drive:
    build:
      context: ./config-drive
      dockerfile: Dockerfile
    image: config-drive
    restart: always
    volumes:
      - ./rancher-cloud-init.yaml:/www/rancher-cloud-init.yaml
    ports:
      - "80:80/tcp"
    hostname: config-drive
  ipxe:
    build:
      context: ./ipxe
      dockerfile: Dockerfile
    image: ipxe
    restart: always
    volumes:
      - ./rancher-loader.pxe:/srv/tftp/rancher-loader.pxe
    ports:
      - "69:69/udp"
    hostname: ipxe
